#!/usr/bin/env bash
set -euo pipefail

ENV_FILE=".env"
ENV_EXAMPLE=".env.example"

echo "╔══════════════════════════════════════════╗"
echo "║        Jablu - Setup Script              ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# Generate a random string
random_string() {
  openssl rand -hex "$1" 2>/dev/null || head -c "$1" /dev/urandom | xxd -p | tr -d '\n'
}

# Copy .env.example if .env doesn't exist
if [ ! -f "$ENV_FILE" ]; then
  echo "→ Creating .env from .env.example..."
  cp "$ENV_EXAMPLE" "$ENV_FILE"
else
  echo "→ .env already exists, updating secrets only..."
fi

# Generate secrets
POSTGRES_PASSWORD=$(random_string 16)
JWT_SECRET=$(random_string 32)
JWT_REFRESH_SECRET=$(random_string 32)
LIVEKIT_API_KEY="API$(random_string 8)"
LIVEKIT_API_SECRET=$(random_string 24)

# Update secrets in .env (cross-platform sed)
update_env() {
  local key="$1"
  local value="$2"
  if grep -q "^${key}=" "$ENV_FILE"; then
    # Only replace if it's still the default placeholder value
    if grep -q "^${key}=changeme" "$ENV_FILE"; then
      if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s|^${key}=changeme.*|${key}=${value}|" "$ENV_FILE"
      else
        sed -i "s|^${key}=changeme.*|${key}=${value}|" "$ENV_FILE"
      fi
      echo "  ✓ Generated ${key}"
    else
      echo "  ○ ${key} already set, skipping"
    fi
  fi
}

SUPERADMIN_USERNAME="admin_$(random_string 4)"
SUPERADMIN_PASSWORD=$(random_string 16)

echo ""
echo "→ Generating secrets..."
update_env "POSTGRES_PASSWORD" "$POSTGRES_PASSWORD"
update_env "JWT_SECRET" "$JWT_SECRET"
update_env "JWT_REFRESH_SECRET" "$JWT_REFRESH_SECRET"
update_env "LIVEKIT_API_KEY" "$LIVEKIT_API_KEY"
update_env "LIVEKIT_API_SECRET" "$LIVEKIT_API_SECRET"
update_env "SUPERADMIN_USERNAME" "$SUPERADMIN_USERNAME"
update_env "SUPERADMIN_PASSWORD" "$SUPERADMIN_PASSWORD"

# Generate VAPID keys for web push
if command -v npx &>/dev/null; then
  if grep -q "^VAPID_PUBLIC_KEY=$" "$ENV_FILE" || ! grep -q "^VAPID_PUBLIC_KEY=" "$ENV_FILE"; then
    VAPID_KEYS=$(npx web-push generate-vapid-keys --json 2>/dev/null || echo "")
    if [ -n "$VAPID_KEYS" ]; then
      VAPID_PUB=$(echo "$VAPID_KEYS" | grep -o '"publicKey":"[^"]*"' | cut -d'"' -f4)
      VAPID_PRIV=$(echo "$VAPID_KEYS" | grep -o '"privateKey":"[^"]*"' | cut -d'"' -f4)
      if [ -n "$VAPID_PUB" ] && [ -n "$VAPID_PRIV" ]; then
        if grep -q "^VAPID_PUBLIC_KEY=" "$ENV_FILE"; then
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^VAPID_PUBLIC_KEY=.*|VAPID_PUBLIC_KEY=${VAPID_PUB}|" "$ENV_FILE"
            sed -i '' "s|^VAPID_PRIVATE_KEY=.*|VAPID_PRIVATE_KEY=${VAPID_PRIV}|" "$ENV_FILE"
          else
            sed -i "s|^VAPID_PUBLIC_KEY=.*|VAPID_PUBLIC_KEY=${VAPID_PUB}|" "$ENV_FILE"
            sed -i "s|^VAPID_PRIVATE_KEY=.*|VAPID_PRIVATE_KEY=${VAPID_PRIV}|" "$ENV_FILE"
          fi
        else
          echo "VAPID_PUBLIC_KEY=${VAPID_PUB}" >> "$ENV_FILE"
          echo "VAPID_PRIVATE_KEY=${VAPID_PRIV}" >> "$ENV_FILE"
        fi
        echo "  ✓ Generated VAPID keys"
      fi
    fi
  else
    echo "  ○ VAPID keys already set, skipping"
  fi
else
  echo "  ⚠ npx not found, skipping VAPID key generation"
  echo "    Run 'npx web-push generate-vapid-keys' manually"
fi

# Update DATABASE_URL with the new password
if grep -q "^DATABASE_URL=postgresql://chat:changeme" "$ENV_FILE"; then
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s|^DATABASE_URL=postgresql://chat:changeme|DATABASE_URL=postgresql://chat:${POSTGRES_PASSWORD}|" "$ENV_FILE"
  else
    sed -i "s|^DATABASE_URL=postgresql://chat:changeme|DATABASE_URL=postgresql://chat:${POSTGRES_PASSWORD}|" "$ENV_FILE"
  fi
  echo "  ✓ Updated DATABASE_URL"
fi

# Hybrid local dev: create .env.development once (same DB password as .env, host → 127.0.0.1)
DEV_FILE=".env.development"
if [ ! -f "$DEV_FILE" ] && grep -q '^DATABASE_URL=postgresql://' "$ENV_FILE"; then
  DB_URL=$(grep '^DATABASE_URL=' "$ENV_FILE" | head -1 | sed 's/^DATABASE_URL=//')
  LOCAL_DB_URL=$(printf '%s' "$DB_URL" | sed 's/@postgres:/@127.0.0.1:/')
  {
    echo "# Auto-generated by setup.sh — local API + Prisma on host → Docker Postgres/Redis."
    echo "# Refresh: pnpm local:sync-env (after you change DATABASE_URL in .env)"
    echo "DATABASE_URL=${LOCAL_DB_URL}"
    echo "REDIS_URL=redis://127.0.0.1:6379"
    echo "SMTP_HOST=127.0.0.1"
  } >"$DEV_FILE"
  echo "  ✓ Created .env.development for pnpm dev + docker-compose.dev.yml"
fi

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║            Setup Complete!               ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo "  1. Edit .env and set SERVER_HOST to your server's IP"
echo "  2. Review SUPERADMIN_USERNAME and SUPERADMIN_PASSWORD in .env"
echo "  3. Local hybrid dev: if .env.development is wrong or missing, run: pnpm local:sync-env"
echo "  4. Run: docker compose --profile dev up -d"
echo "     (use --profile dev to include Mailpit for email testing)"
echo ""
echo "  Web app:     http://\${SERVER_HOST}"
echo "  Admin panel: http://\${SERVER_HOST}/admin"
echo "  Mailpit UI:  http://\${SERVER_HOST}:8025  (dev only)"
echo ""
